baseURL = "http://tabletopdevops.com/"
languageCode = "en-us"
title = "Tabletop DevOps"
theme = "castanet"
googleAnalytics = ""
paginate = "9"
builtFuture = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[permalinks]
    # page "/:filename/"
    about = "/:filename/"
    episode = "/:filename/"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "/books"
    parent = "resources"
[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "/podcasts"
    parent = "resources"

[params]
mainSections = ["episode"]

site_theme = "grey"
site_layout = "grid"
# site_layout = "row"
show_next_upcoming = "true"
# enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "Copyright 2020 [Aaron Aldrich](https://www.crayzeigh.com)"
itunes_subscribe = ""
android_subscribe = ""
spotify_subscribe = ""
google_play_subscribe = ""
stitcher_subscribe = ""
soundcloud_subscribe = ""
pocketcasts_subscribe = ""
mailchimp_subscribe = ""
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Pen and paper, meeples and dice. It's DevOps on your tabletop."
media_prefix = ""
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2020 Aaron Aldrich" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "DevOps for your tabletop" #no markdown or HTML
    itunes_author = "Aaron Aldrich" #no markdown or HTML
    itunes_summary = "DevOps practitioners get together to play some boardgames and try to tease out practical lessons from frivilous fun" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Aaron Aldrich"
    itunes_owner_email = "a.aldrich@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Games"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = ""              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "img/logo.jpg"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "arresteddevops"
    gitlab = "mattstratton"
    facebook = "Arresteddevops"
    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "arresteddevops"
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "ArrestedDevOps"
    pinterest = "nozzleio"
    instagram = "nozzleio"
    youtube = "arresteddevops"
    linkedin = "mattstratton"
    twitch = "mattstratton"

  [params.authors]
    [params.authors.Aaron]
      name	= "Aaron Aldrich"
      thumbnail = "img/host/aaron.png"
      bio = "Aaron is a Cloud Adoption Specialist at Red Hat and founding organizer of DevOpsDays Hartford. He does stuff on the internet and i n real life. He likes overanalyzing boardgames and relating everything to DevOps"
      [params.authors.Aaron.social]
        github = "crayzeigh"
        twitter = "crayzeigh"
        linkedin = "aaronaldrich"
        homepage = "https://crayzeigh.com"
        youtube = "crayzeigh"
        twitch = "crayzeigh"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"